class_name ProgressionDatabase
extends RefCounted
const SCHOOLS=["Embercode","Rime Script","Stormwire","Stone Cant","Radiant Mesh","Umbral Protocol","Restoration","Aethercraft"]
const SPELLS={
"arc_spark":{"name":"Arc Spark","school":"Stormwire","cost":5,"power":1.25,"target":"single enemy","effect":"Charged; chains when upgraded"},"chain_glyph":{"name":"Chain Glyph","school":"Stormwire","cost":10,"power":1.05,"target":"all enemies","effect":"Bonus against machines"},"ember_lance":{"name":"Ember Lance","school":"Embercode","cost":6,"power":1.4,"target":"single enemy","effect":"Applies Burning"},"cinder_wind":{"name":"Cinder Wind","school":"Embercode","cost":11,"power":1.0,"target":"all enemies","effect":"Spreads Burning"},"rime_lock":{"name":"Rime Lock","school":"Rime Script","cost":7,"power":1.2,"target":"single enemy","effect":"Soaked targets may Freeze"},"glacial_ward":{"name":"Glacial Ward","school":"Rime Script","cost":9,"power":0,"target":"all allies","effect":"Barrier and fire resistance"},"stone_needle":{"name":"Stone Needle","school":"Stone Cant","cost":5,"power":1.3,"target":"single enemy","effect":"Pierces armor"},"bastion_rune":{"name":"Bastion Rune","school":"Stone Cant","cost":8,"power":0,"target":"single ally","effect":"Defense up for 3 turns"},"waylight_mend":{"name":"Waylight Mend","school":"Restoration","cost":7,"power":45,"target":"single ally","effect":"Healing; grants barrier when upgraded"},"renewal_mesh":{"name":"Renewal Mesh","school":"Restoration","cost":14,"power":28,"target":"all allies","effect":"Healing over time"},"sun_packet":{"name":"Sun Packet","school":"Radiant Mesh","cost":8,"power":1.45,"target":"single enemy","effect":"Strong against spirits"},"cathedral_field":{"name":"Cathedral Field","school":"Radiant Mesh","cost":16,"power":0,"target":"all allies","effect":"Magic and resistance up"},"shade_drain":{"name":"Shade Drain","school":"Umbral Protocol","cost":8,"power":1.15,"target":"single enemy","effect":"Restores half damage as HP"},"silence_key":{"name":"Silence Key","school":"Umbral Protocol","cost":9,"power":0,"target":"single enemy","effect":"Blocks spell patterns"},"aether_scan":{"name":"Aether Scan","school":"Aethercraft","cost":3,"power":0,"target":"single enemy","effect":"Reveals affinity and bestiary data"},"machine_grace":{"name":"Machine Grace","school":"Aethercraft","cost":12,"power":0,"target":"all allies","effect":"Speed up and MP regeneration"}}
const RARITIES={"common":{"name":"Worn","color":"a7a7a7","mult":1.0,"affixes":0},"uncommon":{"name":"Runed","color":"62ba6f","mult":1.15,"affixes":1},"rare":{"name":"Aetherwoven","color":"5595df","mult":1.35,"affixes":2},"epic":{"name":"Crownforged","color":"a66be0","mult":1.65,"affixes":3},"legendary":{"name":"Myth-Circuit","color":"ed9b3d","mult":2.0,"affixes":3}}
const BASES=[
{"name":"Arcsteel Longsword","slot":"Weapon","type":"Sword","stat":"attack","base":7},{"name":"Rune Pike","slot":"Weapon","type":"Spear","stat":"attack","base":8},{"name":"Signal Daggers","slot":"Weapon","type":"Daggers","stat":"speed","base":7},{"name":"Cantor Staff","slot":"Weapon","type":"Staff","stat":"magic","base":9},{"name":"Sigil Carbine","slot":"Weapon","type":"Runegun","stat":"attack","base":9},{"name":"Circuit Hammer","slot":"Weapon","type":"Hammer","stat":"attack","base":10},{"name":"Arc-lens Circlet","slot":"Head","type":"Circlet","stat":"magic","base":5},{"name":"Visored Greathelm","slot":"Head","type":"Heavy","stat":"defense","base":6},{"name":"Aether-thread Coat","slot":"Body","type":"Light","stat":"speed","base":5},{"name":"Reactor Plate","slot":"Body","type":"Heavy","stat":"defense","base":10},{"name":"Runeplate Gauntlets","slot":"Hands","type":"Medium","stat":"attack","base":5},{"name":"Compiler Gloves","slot":"Hands","type":"Robe","stat":"magic","base":5},{"name":"Neon Greaves","slot":"Feet","type":"Light","stat":"speed","base":5},{"name":"Pilgrim Sabatons","slot":"Feet","type":"Heavy","stat":"defense","base":5},{"name":"Soul-Circuit Locket","slot":"Accessory1","type":"Accessory","stat":"max_mp","base":8},{"name":"Synthetic Heartseal","slot":"Accessory2","type":"Accessory","stat":"max_hp","base":18}]
const AFFIXES=[{"name":"of Vigor","stat":"max_hp","value":18},{"name":"of Clear Signal","stat":"max_mp","value":7},{"name":"of Impact","stat":"attack","value":4},{"name":"of Warding","stat":"defense","value":4},{"name":"of Bright Code","stat":"magic","value":4},{"name":"of Quickening","stat":"speed","value":3},{"name":"Ember-socketed","stat":"fire_power","value":8},{"name":"Storm-grounded","stat":"lightning_resist","value":12}]
const LEGENDARIES=["Crownless King's Circuitblade","Saint Veyra's Neon Halo","The Last Gate's Reactor Mail","Hell-Notary's Brass Seal","Cometheart Staff","Quiet Moon Carbine","Garden-Root Greaves","Orrox Memory Hammer","Lanternwake Tidecloak","Black Star Codex"]
static func build_grid()->Dictionary:
 var nodes={}
 var types=["stat","stat","skill","spell","passive","element","status","job_synergy"]
 for i in 120:
  var ring=i/20;var node_type=types[i%types.size()];var stat_key=["max_hp","max_mp","attack","defense","magic","resistance","speed"][i%7]
  nodes["lattice_%03d"%i]={"id":"lattice_%03d"%i,"name":("%s +%d"%[stat_key.capitalize(),5 if stat_key in ["max_hp","max_mp"] else 1]) if node_type=="stat" else "%s Node %d"%[node_type.capitalize(),i+1],"type":node_type,"cost":1+ring/2,"stat":stat_key,"value":5 if stat_key in ["max_hp","max_mp"] else 1,"spell":SPELLS.keys()[i%SPELLS.size()] if node_type=="spell" else "","links":["lattice_%03d"%maxi(0,i-1),"lattice_%03d"%mini(119,i+1)]}
 return nodes
static func generate_loot(seed_key:String,tier:=1)->Dictionary:
 var rng=RandomNumberGenerator.new();rng.seed=hash(seed_key);var base=BASES[rng.randi_range(0,BASES.size()-1)];var rarity_keys=RARITIES.keys();var rarity_index=clampi(rng.randi_range(0,2)+tier/2,0,4);var rarity_id=rarity_keys[rarity_index];var rarity=RARITIES[rarity_id];var rating=10+tier*8+rng.randi_range(0,8);var stats={base.stat:int(round((base.base+tier)*rarity.mult))};var affix_names=[]
 for j in int(rarity.affixes):var affix=AFFIXES[rng.randi_range(0,AFFIXES.size()-1)];stats[affix.stat]=stats.get(affix.stat,0)+affix.value;affix_names.append(affix.name)
 var name=(LEGENDARIES[abs(hash(seed_key))%LEGENDARIES.size()] if rarity_id=="legendary" else "%s %s %s"%[rarity.name,base.name," ".join(affix_names)])
 return {"instance_id":"gear_"+str(abs(hash(seed_key))),"name":name,"slot":base.slot,"weapon_type":base.type,"rarity":rarity_id,"rating":rating,"stats":stats,"description":"A %s relic where heraldic metal carries luminous rune circuitry."%base.type,"unique_effect":"First action gains a radiant barrier." if rarity_id=="legendary" else ""}

